webOS-ports/luna-webappmanager

- src/extensions/InAppBrowser.js
- src/extensions/inappbrowserextension.cpp
- src/extensions/inappbrowserextension.h
> Always call callbacks for InAppBrowser in the frame the call came from

- src/qml/ApplicationContainer.qml
- src/webapplication.cpp
- src/webapplication.h
- src/webapplicationwindow.cpp
- src/webapplicationwindow.h
> Rework webview creation to render launcher always correctly

- src/qml/ApplicationContainer.qml
> Call correct slot for accepting a database quota

- src/qml/ApplicationContainer.qml
> Make webview background of popupalert windows also transparent

- src/extensions/InAppBrowser.js
Signed-off-by: Achim Königs <garfonso@tratschtante.de>
> InAppBrowser: need to check root window for callbacks, too.

- src/extensions/palmsystemextension.cpp
> Retrieve application base path from application manager

- src/qml/ApplicationContainer.qml
> Reconfigure height of WebView when the geometry of the keyboard changes

- src/qml/ApplicationContainer.qml
> Use LuneOS.Components for the WebView-related dialogs

- src/activity.cpp
- src/extensions/palmsystemextension.cpp
- src/extensions/wifimanager.cpp
Issue #955.
Signed-off-by: Nikolay Nizov <nizovn@gmail.com>
> Fix #955 and some styling

- src/extensions/palmsystemextension.cpp
> addBannerMessage: fix syntax

- src/qml/ApplicationContainer.qml
> Don't display securityUsage if it is not available

- src/webapplicationwindow.cpp
> Setup offline storage path before application is started

- lib/baseextension.h
- src/extensions/palmsystemextension.h
- src/qml/webos-api.js
> webos-api.js: initialize channel synchronously

- src/webapplication.cpp
> Get new window height from QQuickWebEngineNewViewRequest object

- src/extensions/PalmSystem.js
> addBannerMessage: avoid sending null values through WebChannel

- src/qml/ApplicationContainer.qml
> Allow cross-domain access for all system apps

- src/extensions/PalmSystem.js
> PalmSystem: add hooks on stageReady, to put Prelude font as primary

- src/qml/webos-api.js
- src/webapplicationwindow.cpp
> webos-api: better separate sync and async messages' id

- lib/applicationenvironment.h
- src/extensions/InAppBrowser.js
- src/extensions/inappbrowserextension.cpp
- src/qml/InAppBrowser.qml
- src/webapplicationwindow.cpp
- src/webapplicationwindow.h
> InAppBrowser: execute user script also on sub frames

- files/sysbus/org.webosports.webappmanager.json.prv.in
- files/sysbus/org.webosports.webappmanager.json.pub.in
Signed-off-by: Nikolay Nizov <nizovn@gmail.com>
> Allow qtpositioning plugin to communicate with location service

- src/extensions/palmsystemextension.cpp
- src/extensions/palmsystemextension.h
- src/qml/webos-api.js
- src/webapplicationwindow.cpp
- src/webapplicationwindow.h
> Fix window activation; fixes opening of menu.

- src/extensions/palmsystemextension.cpp
To allow playback of sounds etc for banners/dashboards
> Add additional missing parameters for banners

- src/extensions/palmsystemextension.cpp
> addBannerMessage: prepend app path if soundFile path is a relative path

- src/extensions/BluetoothManager.js
- src/extensions/bluetoothmanager.cpp
Pass the key value pair, as intended.
There is a corresponding PR for Settings.
> Bluetooth: Pass proper propertyChanged arguments

- src/qml/ApplicationContainer.qml
Fixes http://issues.webos-ports.org/issues/1099
> ApplicationContainer: fix keyboard visibility on focus

- src/extensions/palmsystemextension.cpp
We don't want to deal with the icon handling here anymore, we'll use a proper solution dealing with more scenarios in Luna-Next-Cardshell directly. 
Signed-off-by: Herman van Hazendonk <github.com@herrie.org>
> Move handling of icon to Luna-Next-Cardshell

- src/extensions/palmsystemextension.cpp
> Implement PalmSystem.enableFullScreenMode

- src/qml/ApplicationContainer.qml
Signed-off-by: Herman van Hazendonk <github.com@herrie.org>
> Only set UA for apps that provide it in appinfo.json & code formatting cleanup

- files/systemd/LunaWebAppManager.service
- src/main.cpp
> Start LunaWebAppManager with --allow-file-access-from-files

- src/extensions/BluetoothManager.js
Signed-off-by: Herman van Hazendonk <github.com@herrie.org>
> BluetoothManager: Add pairingDone function

- src/webapplication.h
- src/webapplicationwindow.cpp
- src/webapplicationwindow.h
This class is now public API since Qt 5.9.
> Fix WebEngine UserScript includes

- files/systemd/luna-webappmanager.service
- src/main.cpp
- src/webapplication.h
- src/webapplicationwindow.cpp
- src/webapplicationwindow.h
Signed-off-by: Herman van Hazendonk <github.com@herrie.org>
> Update to QT 5.9

- files/sysbus/org.webosports.webappmanager.json.prv.in
- files/sysbus/org.webosports.webappmanager.json.pub.in
> Fix LS2 permissions for "" service name
